id: D9FCAB49C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-12-31T06:39:54+00:00'
last_modified: '2022-05-29T07:44:04.800054+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    cd63:
      image_group_id: I1PD95911
      title: རྟེན་ཅིང་འབྲེལ་བར་འབྱུང་བ་དང་པོའི་རྣམ་པར་དབྱེ་བ་བཤད་པ།
      total_pages: 1470
      order: 66
      base_file: cd63.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
