id: P5400BCD3
initial_creation_type: ocr
source_metadata:
  volumes:
    117254b3af1940e1af94709281a89d39:
      base_file: v066.txt
      image_group_id: I1PD95911
      title: རྟེན་ཅིང་འབྲེལ་བར་འབྱུང་བ་དང་པོའི་རྣམ་པར་དབྱེ་བ་བཤད་པ།
      total_pages: 1470
      volume_number: 66
